"""Cross-artifact analysis — structural consistency checks (offline, no LLM).

Split out of :mod:`monolith.workflow` so the validation logic is a single,
cohesive responsibility separate from path conventions and scaffolding.

Findings are structured values (:class:`Finding` with a :class:`Severity`), not
prefixed strings, so callers branch on ``finding.severity`` instead of parsing
text — and the on-screen prefix is a presentation detail of ``__str__``.
"""

from __future__ import annotations

import enum
import os
import re
from dataclasses import dataclass
from typing import List, Optional

from monolith.workflow import (
    CONTRACTS_DIR,
    PIPELINE_ARTIFACTS,
    artifact_path,
    constitution_path,
    feature_dir,
)

_PLACEHOLDER_RE = re.compile(r"<!--.*?-->|\bTODO\b|\bTBD\b", re.MULTILINE | re.DOTALL)
_HEADING_RE = re.compile(r"^#{1,6}\s+\S", re.MULTILINE)
_CHECKBOX_RE = re.compile(r"- \[[ x]\]")


class Severity(enum.Enum):
    """Severity of a single analysis finding, ordered least to most urgent."""

    OK = "OK"
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"


@dataclass(frozen=True)
class Finding:
    """One analysis result: a severity plus a human-readable message."""

    severity: Severity
    message: str

    def __str__(self) -> str:
        return f"{self.severity.value:<6}{self.message}"


@dataclass
class ArtifactStatus:
    name: str
    exists: bool
    word_count: int = 0
    heading_count: int = 0
    checkbox_count: int = 0
    unfilled: bool = False


def _read_file(path: str) -> Optional[str]:
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def _status_from_text(name: str, text: str) -> ArtifactStatus:
    stripped = _PLACEHOLDER_RE.sub("", text)
    words = len(stripped.split())
    return ArtifactStatus(
        name=name,
        exists=True,
        word_count=words,
        heading_count=len(_HEADING_RE.findall(text)),
        checkbox_count=len(_CHECKBOX_RE.findall(text)),
        # Unfilled = still has generator comment AND very few real words.
        unfilled="Generated by" in text and words < 60,
    )


def _artifact_status(root: str, feature: str, name: str) -> ArtifactStatus:
    text = _read_file(artifact_path(root, feature, name))
    if text is None:
        return ArtifactStatus(name=name, exists=False)
    return _status_from_text(name, text)


def analyze_feature(root: str, feature: str) -> List[Finding]:
    """Return structured findings for a feature's artifact set."""
    findings: List[Finding] = []

    # Constitution
    if os.path.exists(constitution_path(root)):
        findings.append(Finding(Severity.OK, "constitution.md exists"))
    else:
        findings.append(
            Finding(Severity.WARN, "constitution.md missing — run `monolith constitution`")
        )

    # Required pipeline artifacts
    for name in PIPELINE_ARTIFACTS:
        s = _artifact_status(root, feature, name)

        # tasks.md fallback: `monolith plan` writes the project-root TASKS.md,
        # not specs/<feature>/tasks.md. Accept the root file as equivalent.
        if not s.exists and name == "tasks.md":
            root_tasks = os.path.join(root, "TASKS.md")
            text = _read_file(root_tasks)  # read once (avoids a TOCTOU re-read)
            if text is not None:
                s = _status_from_text("tasks.md (root TASKS.md)", text)

        if not s.exists:
            if name == "spec.md":
                hint = f"run `monolith specify {feature}`"
            elif name == "plan.md":
                hint = f"run `monolith plan <prd>` (or fill specs/{feature}/plan.md)"
            else:
                hint = f"run `monolith plan specs/{feature}/spec.md`"
            findings.append(Finding(Severity.ERROR, f"{name} missing — {hint}"))
        elif s.unfilled:
            findings.append(
                Finding(Severity.WARN, f"{name} has unfilled template placeholders")
            )
        elif s.word_count < 30:
            findings.append(Finding(Severity.WARN, f"{name} is very thin ({s.word_count} words)"))
        else:
            cb = f", {s.checkbox_count} checkboxes" if s.checkbox_count else ""
            findings.append(
                Finding(
                    Severity.OK,
                    f"{s.name}  ({s.word_count} words, {s.heading_count} sections{cb})",
                )
            )

    # Optional artifacts
    dm = _artifact_status(root, feature, "data-model.md")
    if dm.exists and not dm.unfilled:
        findings.append(Finding(Severity.OK, f"data-model.md  ({dm.word_count} words)"))
    elif dm.exists:
        findings.append(Finding(Severity.WARN, "data-model.md has unfilled template placeholders"))
    else:
        findings.append(
            Finding(
                Severity.INFO,
                f"data-model.md absent — add with `monolith specify --data-model {feature}`",
            )
        )

    contracts_dir = os.path.join(feature_dir(root, feature), CONTRACTS_DIR)
    if os.path.isdir(contracts_dir):
        contracts = [f for f in os.listdir(contracts_dir) if f != "README.md"]
        n = len(contracts)
        findings.append(
            Finding(Severity.OK, f"contracts/  ({n} contract file{'s' if n != 1 else ''})")
        )
    else:
        findings.append(
            Finding(
                Severity.INFO,
                f"contracts/ absent — add with `monolith specify --contracts {feature}`",
            )
        )

    return findings


# ---------------------------------------------------------------------------
# Checklist generation
# ---------------------------------------------------------------------------

_CHECKLIST_TEMPLATE = """\
# Quality Checklist: {feature}

## Spec and Planning
- [{spec_check}] `spec.md` written and reviewed
- [{plan_check}] `plan.md` matches spec requirements
- [{tasks_check}] `tasks.md` covers all spec sections
- [ ] All open questions resolved (no `?` placeholders in spec)
- [ ] Non-goals explicitly listed

## Implementation
- [ ] All acceptance criteria from spec satisfied
- [ ] Edge cases from `plan.md` handled in code
- [ ] No TODO / FIXME / HACK left in committed files

## Quality Gates
- [ ] Tests pass (`monolith run -- pytest` or equivalent)
- [ ] Lint/type-check passes (`monolith run -- ruff check .`)
- [ ] `monolith doctor` reports no issues
- [ ] `monolith analyze {feature}` reports no ERRORs

## Review
- [ ] PR description references this feature's spec
- [ ] Reviewer confirmed implementation matches spec
- [ ] CHANGELOG updated

_Generated by Monolith for `{feature}`. Edit as needed._
"""


def generate_checklist(root: str, feature: str) -> str:
    """Return a Markdown quality checklist for ``feature``."""

    def _box(name: str) -> str:
        return "x" if _artifact_status(root, feature, name).exists else " "

    return _CHECKLIST_TEMPLATE.format(
        feature=feature,
        spec_check=_box("spec.md"),
        plan_check=_box("plan.md"),
        tasks_check=_box("tasks.md"),
    )
