"""Spec-Driven Development workflow — structured per-feature artifact management.

Monolith's SDD pipeline mirrors spec-kit's methodology adapted for Monolith's
offline, dependency-free philosophy:

    constitution → specify → clarify → plan → analyze → tasks → implement

Each feature lives under ``specs/<feature>/`` with standard artifact files:
    spec.md        functional requirements and user stories
    plan.md        technical architecture and stack decisions
    tasks.md       actionable task breakdown with dependencies
    data-model.md  entity and data model (optional)
    contracts/     API contracts, one file per endpoint (optional)

All scaffolding is template-based and deterministic — no LLM calls, no network.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Directory / path conventions
# ---------------------------------------------------------------------------

SPECS_DIR = "specs"
CONSTITUTION_PATH = os.path.join(".monolith", "memory", "constitution.md")
CONTRACTS_DIR = "contracts"

#: Artifact names that form the required pipeline.
PIPELINE_ARTIFACTS = ("spec.md", "plan.md", "tasks.md")
#: Optional artifacts that improve coverage but are not blocking.
OPTIONAL_ARTIFACTS = ("data-model.md",)
ALL_ARTIFACTS = PIPELINE_ARTIFACTS + OPTIONAL_ARTIFACTS


def feature_dir(root: str, feature: str) -> str:
    return os.path.join(root, SPECS_DIR, feature)


def artifact_path(root: str, feature: str, artifact: str) -> str:
    return os.path.join(feature_dir(root, feature), artifact)


def constitution_path(root: str) -> str:
    return os.path.join(root, CONSTITUTION_PATH)


def list_features(root: str) -> List[str]:
    """Return sorted feature names found under ``specs/``."""
    specs_root = os.path.join(root, SPECS_DIR)
    if not os.path.isdir(specs_root):
        return []
    return sorted(
        name for name in os.listdir(specs_root)
        if os.path.isdir(os.path.join(specs_root, name))
    )


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_CONSTITUTION_TEMPLATE = """\
<!-- Generated by `monolith constitution`. Edit freely — this file is yours. -->
# Project Constitution

## Mission
<!-- One sentence: what problem does this project solve and for whom? -->

## Core Principles
<!-- 3–7 non-negotiable engineering rules. Examples: -->
- Correctness over cleverness — prefer the obvious solution.
- Tests are mandatory for every public interface.
- No external dependency without explicit justification.
- Performance is measured, not assumed.

## Code Quality Standards
- All public functions have a docstring.
- No commented-out code in committed files.
- Lint and type-check must pass before merge.

## Definition of Done
A task is done when:
- [ ] Implementation matches the spec acceptance criteria.
- [ ] Tests pass (unit + integration where applicable).
- [ ] `monolith doctor` reports no issues.
- [ ] PR reviewed and approved.
"""

_SPEC_TEMPLATE = """\
<!-- Generated by `monolith specify {feature}`. Fill in each section. -->
# Feature: {feature}

## Problem Statement
<!-- What user pain or gap does this feature address? One paragraph. -->

## Goals
<!-- What must be true when this feature ships? Bullet list. -->
-

## Non-Goals
<!-- What are we explicitly NOT building in this iteration? -->
-

## User Stories
<!-- As a <role>, I want <action> so that <outcome>. -->
- As a , I want  so that .

## Functional Requirements
<!-- Numbered, specific, testable. Each one maps to plan sections + tasks. -->
1.

## Acceptance Criteria
<!-- Checkbox list. These drive the quality checklist. -->
- [ ]

## Open Questions
<!-- Anything unresolved. Run `monolith clarify {feature}` or `/monolith.clarify`. -->
-
"""

_PLAN_TEMPLATE = """\
<!-- Generated by `monolith plan`. Fill in after spec.md is finalised. -->
# Plan: {feature}

## Architecture Overview
<!-- One paragraph: the approach and key trade-offs. -->

## Tech Stack Decisions
| Decision | Choice | Rationale |
|---|---|---|
|  |  |  |

## Component Design
<!-- One section per major component / module. -->

## Data Flow
<!-- How does data move through the system? Prose or pseudocode. -->

## Edge Cases and Risks
<!-- What can go wrong? How do we handle it? -->

## Out of Scope
<!-- Anything deferred to a later iteration. -->
"""

_DATA_MODEL_TEMPLATE = """\
<!-- Generated by `monolith specify --data-model {feature}`. -->
# Data Model: {feature}

## Entities
<!-- One sub-section per entity. -->

### EntityName
| Field | Type | Required | Description |
|---|---|---|---|
|  |  |  |  |

## Relationships
<!-- Describe how entities relate: 1:1, 1:N, N:M. -->

## Validation Rules
<!-- Per-field constraints enforced at the application layer. -->
"""

_CONTRACTS_README_TEMPLATE = """\
# Contracts: {feature}

Place API contracts here — one file per endpoint or event.

## Naming Convention
- REST endpoint: `<METHOD>-<resource>.md`   e.g. `POST-users.md`
- GraphQL:       `<operation>.graphql`
- Events:        `<event-name>.md`           e.g. `user-created.md`
"""

_CHECKLIST_TEMPLATE = """\
# Quality Checklist: {feature}

## Spec and Planning
- [{spec_check}] `spec.md` written and reviewed
- [{plan_check}] `plan.md` matches spec requirements
- [{tasks_check}] `tasks.md` covers all spec sections
- [ ] All open questions resolved (no `?` placeholders in spec)
- [ ] Non-goals explicitly listed

## Implementation
- [ ] All acceptance criteria from spec satisfied
- [ ] Edge cases from `plan.md` handled in code
- [ ] No TODO / FIXME / HACK left in committed files

## Quality Gates
- [ ] Tests pass (`monolith run -- pytest` or equivalent)
- [ ] Lint/type-check passes (`monolith run -- ruff check .`)
- [ ] `monolith doctor` reports no issues
- [ ] `monolith analyze {feature}` reports no ERRORs

## Review
- [ ] PR description references this feature's spec
- [ ] Reviewer confirmed implementation matches spec
- [ ] CHANGELOG updated

_Generated by Monolith for `{feature}`. Edit as needed._
"""


# ---------------------------------------------------------------------------
# Scaffold helpers
# ---------------------------------------------------------------------------

def _write_if_absent(path: str, content: str) -> Tuple[bool, str]:
    """Write ``content`` to ``path`` only if it does not already exist.

    Returns ``(was_created, path)``.
    """
    if os.path.exists(path):
        return False, path
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return True, path


def scaffold_constitution(root: str) -> Tuple[bool, str]:
    return _write_if_absent(constitution_path(root), _CONSTITUTION_TEMPLATE)


def scaffold_spec(root: str, feature: str) -> Tuple[bool, str]:
    return _write_if_absent(
        artifact_path(root, feature, "spec.md"),
        _SPEC_TEMPLATE.format(feature=feature),
    )


def scaffold_plan(root: str, feature: str) -> Tuple[bool, str]:
    return _write_if_absent(
        artifact_path(root, feature, "plan.md"),
        _PLAN_TEMPLATE.format(feature=feature),
    )


def scaffold_data_model(root: str, feature: str) -> Tuple[bool, str]:
    return _write_if_absent(
        artifact_path(root, feature, "data-model.md"),
        _DATA_MODEL_TEMPLATE.format(feature=feature),
    )


def scaffold_contracts(root: str, feature: str) -> Tuple[bool, str]:
    path = os.path.join(feature_dir(root, feature), CONTRACTS_DIR, "README.md")
    return _write_if_absent(path, _CONTRACTS_README_TEMPLATE.format(feature=feature))


# ---------------------------------------------------------------------------
# Analyze — structural consistency check (offline, no LLM)
# ---------------------------------------------------------------------------

_PLACEHOLDER_RE = re.compile(
    r"<!--.*?-->|\bTODO\b|\bTBD\b",
    re.MULTILINE | re.DOTALL,
)
_HEADING_RE = re.compile(r"^#{1,6}\s+\S", re.MULTILINE)
_CHECKBOX_RE = re.compile(r"- \[[ x]\]")


@dataclass
class ArtifactStatus:
    name: str
    exists: bool
    word_count: int = 0
    heading_count: int = 0
    checkbox_count: int = 0
    unfilled: bool = False


def _read_file(path: str) -> Optional[str]:
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def _artifact_status(root: str, feature: str, name: str) -> ArtifactStatus:
    path = artifact_path(root, feature, name)
    text = _read_file(path)
    if text is None:
        return ArtifactStatus(name=name, exists=False)
    stripped = _PLACEHOLDER_RE.sub("", text)
    words = len(stripped.split())
    headings = len(_HEADING_RE.findall(text))
    checkboxes = len(_CHECKBOX_RE.findall(text))
    # Unfilled = still has generator comment AND very few real words.
    unfilled = "Generated by" in text and words < 60
    return ArtifactStatus(
        name=name,
        exists=True,
        word_count=words,
        heading_count=headings,
        checkbox_count=checkboxes,
        unfilled=unfilled,
    )


def analyze_feature(root: str, feature: str) -> List[str]:
    """Return plain-English findings for a feature's artifact set.

    Each finding is prefixed with ``OK``, ``WARN``, ``ERROR``, or ``INFO``.
    """
    findings: List[str] = []

    # Constitution
    if os.path.exists(constitution_path(root)):
        findings.append("OK    constitution.md exists")
    else:
        findings.append("WARN  constitution.md missing — run `monolith constitution`")

    # Required pipeline artifacts
    for name in PIPELINE_ARTIFACTS:
        s = _artifact_status(root, feature, name)
        if not s.exists:
            if name == "spec.md":
                hint = f"run `monolith specify {feature}`"
            elif name == "plan.md":
                hint = f"run `monolith plan <prd>` (or fill specs/{feature}/plan.md)"
            else:
                hint = "run `monolith tasks` after plan"
            findings.append(f"ERROR  {name} missing — {hint}")
        elif s.unfilled:
            findings.append(f"WARN  {name} has unfilled template placeholders")
        elif s.word_count < 30:
            findings.append(f"WARN  {name} is very thin ({s.word_count} words)")
        else:
            cb = f", {s.checkbox_count} checkboxes" if s.checkbox_count else ""
            findings.append(
                f"OK    {name}  ({s.word_count} words, {s.heading_count} sections{cb})"
            )

    # Optional artifacts
    dm = _artifact_status(root, feature, "data-model.md")
    if dm.exists and not dm.unfilled:
        findings.append(f"OK    data-model.md  ({dm.word_count} words)")
    elif dm.exists:
        findings.append("WARN  data-model.md has unfilled template placeholders")
    else:
        findings.append(
            f"INFO  data-model.md absent — add with `monolith specify --data-model {feature}`"
        )

    contracts_dir = os.path.join(feature_dir(root, feature), CONTRACTS_DIR)
    if os.path.isdir(contracts_dir):
        contracts = [f for f in os.listdir(contracts_dir) if f != "README.md"]
        n = len(contracts)
        findings.append(f"OK    contracts/  ({n} contract file{'s' if n != 1 else ''})")
    else:
        findings.append(
            f"INFO  contracts/ absent — add with `monolith specify --contracts {feature}`"
        )

    return findings


# ---------------------------------------------------------------------------
# Checklist generation
# ---------------------------------------------------------------------------

def generate_checklist(root: str, feature: str) -> str:
    """Return a Markdown quality checklist for ``feature``."""
    spec_ok = _artifact_status(root, feature, "spec.md").exists
    plan_ok = _artifact_status(root, feature, "plan.md").exists
    tasks_ok = _artifact_status(root, feature, "tasks.md").exists

    def _box(flag: bool) -> str:
        return "x" if flag else " "

    return _CHECKLIST_TEMPLATE.format(
        feature=feature,
        spec_check=_box(spec_ok),
        plan_check=_box(plan_ok),
        tasks_check=_box(tasks_ok),
    )
