"""Base adapter.

An adapter knows one agent's native instruction file and how to render the
Monolith ruleset into it. Writes are idempotent: the managed content lives
between HTML-comment markers, so re-running `apply` updates only that block
and never clobbers a user's own notes in the same file.
"""

import os

from monolith.profiles import get_profile
from monolith.rules import OVERRIDE_NOTE, get_rule

START = "<!-- monolith:start -->"
END = "<!-- monolith:end -->"
_GENERATED_NOTE = (
    "<!-- Generated by Monolith. Do not edit between the markers; "
    "run `monolith apply` to regenerate. -->"
)


class Adapter:
    #: short key used on the command line (`--agent <key>`)
    key = ""
    #: human-readable agent name
    label = ""
    #: path, relative to the project root, of the agent's instruction file
    target_path = ""

    def intro(self):
        """Agent-specific framing line above the rules."""
        return "The following rules reduce token usage. Apply them to every response."

    def render_block(self, profile_name, custom_rules=None):
        """Return the full managed block (markers included) as a string."""
        profile = get_profile(profile_name)
        if profile is None:
            raise ValueError("unknown profile: %s" % profile_name)
        custom_rules = custom_rules or []

        lines = [
            START,
            _GENERATED_NOTE,
            "## Token-Efficiency Rules (Monolith - profile: %s)" % profile_name,
            "",
            self.intro(),
            "",
            "_%s_" % profile["tone"],
            "",
        ]
        for rule_id in profile["rule_ids"]:
            text = get_rule(rule_id)
            if text:
                lines.append("- %s" % text)
        for custom in custom_rules:
            lines.append("- %s" % custom)
        lines += [
            "",
            "> %s" % OVERRIDE_NOTE,
            END,
        ]
        return "\n".join(lines) + "\n"

    # -- file operations -------------------------------------------------

    def _abs_path(self, root):
        return os.path.join(root, self.target_path)

    def apply(self, root, profile_name, custom_rules=None):
        """Write/update the managed block in the target file.

        Returns "created" or "updated" describing the outcome.
        """
        block = self.render_block(profile_name, custom_rules)
        path = self._abs_path(root)
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)

        if not os.path.exists(path):
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(block)
            return "created"

        with open(path, "r", encoding="utf-8") as fh:
            content = fh.read()

        if START in content and END in content:
            pre = content.split(START)[0]
            post = content.split(END, 1)[1]
            new_content = pre + block.rstrip("\n") + post
            outcome = "updated"
        else:
            sep = "" if content.endswith("\n\n") else ("\n" if content.endswith("\n") else "\n\n")
            new_content = content + sep + block
            outcome = "updated"

        with open(path, "w", encoding="utf-8") as fh:
            fh.write(new_content)
        return outcome

    def status(self, root):
        """Return a dict describing whether the block is present and healthy."""
        path = self._abs_path(root)
        if not os.path.exists(path):
            return {"agent": self.key, "path": self.target_path, "ok": False,
                    "reason": "file missing"}
        with open(path, "r", encoding="utf-8") as fh:
            content = fh.read()
        if START in content and END in content:
            return {"agent": self.key, "path": self.target_path, "ok": True,
                    "reason": "managed block present"}
        return {"agent": self.key, "path": self.target_path, "ok": False,
                "reason": "file exists but no Monolith block"}

    def file_present(self, root):
        return os.path.exists(self._abs_path(root))
