"""Compiler base class — renders the directive set into one agent's file.

Each concrete agent compiler subclasses :class:`Compiler`, declares where its
native instruction file lives, and gets idempotent, non-destructive writes for
free.

How writes stay safe
---------------------
The generated content is wrapped in HTML-comment markers. On re-apply we
replace *only* the text between those markers using a single pre-compiled
regex pass, so:

* a user's own notes elsewhere in the file are never touched, and
* repeated ``apply`` runs never stack duplicate blocks.
"""

from __future__ import annotations

import os
import re
from typing import Sequence

from monolith.compression import Tier, get_tier
from monolith.directives import OVERRIDE_NOTE, directive_text

# Marker comments that bound the managed region of every generated file.
START = "<!-- monolith:start -->"
END = "<!-- monolith:end -->"

# Pre-compiled once: matches an existing managed block (markers included) so we
# can swap it in a single pass instead of splitting the string twice.
_BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)

_GENERATED_NOTE = (
    "<!-- Generated by Monolith. Do not edit between the markers; "
    "run `monolith apply` to regenerate. -->"
)


class Compiler:
    """Base class for agent compilers. Subclasses set the class attributes."""

    #: short key used on the command line (``--agent <key>``)
    key: str = ""
    #: human-readable agent name shown in command output
    label: str = ""
    #: path, relative to the project root, of the agent's instruction file
    target_path: str = ""

    # -- content rendering --------------------------------------------------

    def preamble(self) -> str:
        """Agent-specific framing line shown above the directive list.

        Override per agent to phrase the instruction in that agent's voice.
        """
        return "The following rules reduce token usage. Apply them to every response."

    def render(self, tier_name: str, extra_rules: Sequence[str] = ()) -> str:
        """Return the full managed block (markers included) for ``tier_name``.

        Raises ``ValueError`` if the tier is unknown.
        """
        tier: Tier | None = get_tier(tier_name)
        if tier is None:
            raise ValueError(f"unknown tier: {tier_name!r}")

        # Build directive bullets once. ``directive_text`` returns None for an
        # unknown id; we skip those defensively rather than emit a blank bullet.
        bullets = [
            f"- {text}"
            for text in (directive_text(did) for did in tier.directive_ids)
            if text
        ]
        bullets += [f"- {rule}" for rule in extra_rules]

        lines = [
            START,
            _GENERATED_NOTE,
            f"## Token-Efficiency Rules (Monolith - tier: {tier_name})",
            "",
            self.preamble(),
            "",
            f"_{tier.tone}_",
            "",
            *bullets,
            "",
            f"> {OVERRIDE_NOTE}",
            END,
        ]
        return "\n".join(lines) + "\n"

    # -- filesystem operations ---------------------------------------------

    def _path(self, root: str) -> str:
        return os.path.join(root, self.target_path)

    def file_present(self, root: str) -> bool:
        """Return whether this agent's instruction file exists under ``root``."""
        return os.path.exists(self._path(root))

    def apply(self, root: str, tier_name: str, extra_rules: Sequence[str] = ()) -> str:
        """Write/update the managed block. Returns ``"created"`` or ``"updated"``.

        The operation is idempotent: running it twice yields the same file.
        """
        block = self.render(tier_name, extra_rules)
        path = self._path(root)
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)

        # New file -> just write the block.
        if not os.path.exists(path):
            self._write(path, block)
            return "created"

        original = self._read(path)

        if _BLOCK_RE.search(original):
            # Replace the existing block in one pass. ``\g<0>`` is avoided; we
            # substitute the literal new block (count=1 guards against the rare
            # case of duplicate markers from manual edits).
            updated = _BLOCK_RE.sub(lambda _: block.rstrip("\n"), original, count=1)
        else:
            # No block yet: append, normalising to exactly one trailing blank
            # line between prior content and the new block.
            updated = original.rstrip("\n") + "\n\n" + block

        if updated != original:
            self._write(path, updated)
        return "updated"

    def status(self, root: str) -> dict:
        """Return a health report dict for this agent's file."""
        path = self._path(root)
        if not os.path.exists(path):
            return self._report(False, "file missing")
        if _BLOCK_RE.search(self._read(path)):
            return self._report(True, "managed block present")
        return self._report(False, "file exists but no Monolith block")

    # -- tiny IO helpers (single place to tweak encoding/newlines) ----------

    @staticmethod
    def _read(path: str) -> str:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()

    @staticmethod
    def _write(path: str, text: str) -> None:
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(text)

    def _report(self, ok: bool, reason: str) -> dict:
        return {"agent": self.key, "path": self.target_path, "ok": ok, "reason": reason}
